_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 360000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.04
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("voc_2012_trainval",) #voc_2012_train
  TRAIN_UNLABEL: ("Watercolor_train",) #Clipart1k_train
  TEST: ("Watercolor_test",) #Clipart1k_test
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 1000
